---
title: Presentations
---

![Photo by <a href="https://unsplash.com/@matthewosborn?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Matthew Osborn</a> on <a href="https://unsplash.com/photos/people-sitting-on-chair-in-front-of-table-wMRIcT86SWU?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Unsplash</a>](https://images.unsplash.com/photo-1591115765373-5207764f72e7?q=80&w=1740&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D){.crop}

Presentations on Open Science and archaeology topics will be given in the afternoon of the first day.

We welcome all presentations on the topic of Open Science in Archaeology.
Topics can range from Open Science
success stories (open research and education), research related to open science,
useful tools (R and Python packages), and more. The sky is the limit! (figuratively speaking;
topics should ideally be related to Open Science and/or archaeology)
Descriptions will not be published, so we welcome relevant presentations that have already
been presented at other venues; reduce, reuse, recycle!

We also welcome pitches, where the presenter pitches an idea or problem for the discussion or
collaboration on an unconference output.

If there are more proposed talks than time allows, we will have a board available on the morning of
the Unconference where participants can vote for the presentations they would like to attend.

## Guidelines for presenters

Presentations are 5-10 minutes. There will be no questions after the talks,
as the next item in the programme involves discussions on the topics of the talks, and
questions can be asked during this time. We also encourage further discussion during
networking. If you would like to encourage a discussion from your presentation, make
sure to pose some questions or items of discussion at the end of your talk.

Pitches should should give a quick overview of the
discussion topic, problem, or a proposed output (such as a blog, book). Why is it relevant?
What kind of help/expertise is needed? What is in it for the participants?

