---
title: Registration
---

In keeping with the spirit of Unconferences, participation is completely free.
We therefore encourage anyone, with the means to do so, to make a donation to
the [Black Trowel Collective](https://blacktrowelcollective.wordpress.com/microgrants/).

From the Black Trowel Collective:

> We are a collective of archaeologists committed to the active support of
archaeology students from working-class and historically looted communities
who are both regularly excluded by traditional scholarship and academic programs,
or who require more economic support than those resources cover.

## Presenters

**Registration for presenters will open...**

We welcome all presentations on the topic of Open Science in Archaeology.
During registration you will be able to provide a description of the presentation. There
are no requirements for this description. Topics can range from Open Science
success stories (open research and education), research related to open science,
useful tools (R and python packages), and more. The sky is the limit! (figuratively speaking;
topics should ideally be related to Open Science and/or archaeology)
Descriptions will not be published, so we welcome relevant presentations that have already
been presented at other venues; please do re-use previous presentations!


Presentations will be a maximum of 10 minutes. There will be no questions after the talks,
as the next item in the programme involves discussions on the topics of the talks, and
questions can be asked during this time.

If there are more proposed talks than time allows, we will have a board where participants
can vote for the presentations they would like to attend on the morning of the Unconference.


## Workshop hosts

**Registration for workshop hosts is open**

We welcome proposed workshops on any topic related to Open Science practices (e.g.,
FAIR data, open source tools, etc). We will be able to accommodate 3-4 workshops
of around 45-90 mins in length. All proposed workshop topics will be voted on by
participants, and the top 3 will be given at the Unconference.

## Registration

**General registration will open...**

Registration will be initially open for presenters and workshop hosts. Registration
for all attendees will open 1st of August.

<!-- embed registration code from Eventbrite -->