---
title: Workshops
---

![Photo by <a href="https://unsplash.com/@jasongoodman_youxventures?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Jason Goodman</a> on <a href="https://unsplash.com/photos/man-standing-behind-flat-screen-computer-monitor-bzqU01v-G54?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Unsplash</a>](https://images.unsplash.com/photo-1557426272-fc759fdf7a8d?q=80&w=1740&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D){.crop}

Workshops on Open Science topics will be given in the morning of the first day.
The main goal of the workshops is to help participants become more comfortable
in practicing Open Research, and provide an introduction to, or a more advanced exploration of,
available resources and open source tools. These can be specific to archaeology
or more general resources.

You can register for the workshop you want to join during [registration](registration.qmd).

## Workshop topics

### Making your graphs and plots reproducible with Python

Host: Alex Brandsen

Want to make beautiful graphs, that scale well in publications? Hate making graphs in Excel,
and want to easily adapt to new data? Then this is the workshop for you! Learn the basics of
Python (no experience needed), load in some tabular data, and learn how to make reproducible
graphs and plots.

### Can we openly share archaeological location data?

Hosts: Pascal Flohr & Adam Benfer

Publishing research data openly is an important part of Open Science and helps to make data FAIR (Findable, Accessible, Interoperable, and Reusable). However, FAIR data is not necessarily open, and sensitive data (like personal data) does not have to, and should not, be shared openly. Location data can potentially be harmful to share -think of increased looting- but at the same time it is essential to understand and reuse many archaeological datasets. So how to strike the balance here between being as open as possible and as closed as necessary?  

In this interactive workshop we will focus on finding solutions to this question. We look at other fields where this is relevant, like ecology (location of endangered species) and how they are dealing with this, as well as several archaeological case studies. This will form a framework for deciding if location data can be fully published or should be (partially) obscured. We will then introduce potential practical solutions to obscuring location data to different levels and finally discuss with the participants how to establish agreements and maintain trust when working with international partners.

### Convert Archaeological Data to RDF

Host: Alexandre Peixe

Have you ever seen data represented as a knowledge graph and asked yourself,
"How do they do that?" It’s your lucky day! This workshop is perfect for you!
Join us to learn how to feed your data into a knowledge graph using OntoText
Refine and visualize it with GraphDB. You can even bring your data, and by the
end, we can brainstorm together how it could be shaped into a format that improves
context and relationship visualization and may allow enhanced data integration
and retrieval.

### Georeferencing archaeological plans with Allmaps

Host: Jules Schoonman

Many historical archaeological publications have been digitized by libraries and
archives around the world. If such institutions support the standards of the
International Image Interoperability Framework (IIIF) these resources can be
georeferenced using the open source tools of Allmaps. This workshop will guide you
through the process, using the collection of digitized archaeological literature of
Heidelberg University as an example. It will include a demonstration of opening a
resource in QGIS using the XYZ tile proxy.
